package com.sma2.sma2.DataAccess;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDICINE_DA".
*/
public class MedicineDADao extends AbstractDao<MedicineDA, Long> {

    public static final String TABLENAME = "MEDICINE_DA";

    /**
     * Properties of entity MedicineDA.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PatientDAId = new Property(1, long.class, "patientDAId", false, "PATIENT_DAID");
        public final static Property Deleted = new Property(2, boolean.class, "deleted", false, "DELETED");
        public final static Property MedicineName = new Property(3, String.class, "medicineName", false, "MEDICINE_NAME");
        public final static Property Dose = new Property(4, int.class, "dose", false, "DOSE");
        public final static Property IntakeTime = new Property(5, int.class, "intakeTime", false, "INTAKE_TIME");
    }

    private DaoSession daoSession;


    public MedicineDADao(DaoConfig config) {
        super(config);
    }
    
    public MedicineDADao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDICINE_DA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PATIENT_DAID\" INTEGER NOT NULL ," + // 1: patientDAId
                "\"DELETED\" INTEGER NOT NULL ," + // 2: deleted
                "\"MEDICINE_NAME\" TEXT," + // 3: medicineName
                "\"DOSE\" INTEGER NOT NULL ," + // 4: dose
                "\"INTAKE_TIME\" INTEGER NOT NULL );"); // 5: intakeTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDICINE_DA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MedicineDA entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPatientDAId());
        stmt.bindLong(3, entity.getDeleted() ? 1L: 0L);
 
        String medicineName = entity.getMedicineName();
        if (medicineName != null) {
            stmt.bindString(4, medicineName);
        }
        stmt.bindLong(5, entity.getDose());
        stmt.bindLong(6, entity.getIntakeTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MedicineDA entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPatientDAId());
        stmt.bindLong(3, entity.getDeleted() ? 1L: 0L);
 
        String medicineName = entity.getMedicineName();
        if (medicineName != null) {
            stmt.bindString(4, medicineName);
        }
        stmt.bindLong(5, entity.getDose());
        stmt.bindLong(6, entity.getIntakeTime());
    }

    @Override
    protected final void attachEntity(MedicineDA entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MedicineDA readEntity(Cursor cursor, int offset) {
        MedicineDA entity = new MedicineDA( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // patientDAId
            cursor.getShort(offset + 2) != 0, // deleted
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // medicineName
            cursor.getInt(offset + 4), // dose
            cursor.getInt(offset + 5) // intakeTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MedicineDA entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPatientDAId(cursor.getLong(offset + 1));
        entity.setDeleted(cursor.getShort(offset + 2) != 0);
        entity.setMedicineName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDose(cursor.getInt(offset + 4));
        entity.setIntakeTime(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MedicineDA entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MedicineDA entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MedicineDA entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPatientDADao().getAllColumns());
            builder.append(" FROM MEDICINE_DA T");
            builder.append(" LEFT JOIN PATIENT_DA T0 ON T.\"PATIENT_DAID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MedicineDA loadCurrentDeep(Cursor cursor, boolean lock) {
        MedicineDA entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PatientDA patientDA = loadCurrentOther(daoSession.getPatientDADao(), cursor, offset);
         if(patientDA != null) {
            entity.setPatientDA(patientDA);
        }

        return entity;    
    }

    public MedicineDA loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MedicineDA> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MedicineDA> list = new ArrayList<MedicineDA>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MedicineDA> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MedicineDA> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
